ALTER TABLE[Users]
DROP CONSTRAINT PK__Users__3214EC07B7A1F1D9 --REMOVING A PK AS AN ATTRIBUTE TO THE Id COLUMN

ALTER TABLE[Users]
ADD CONSTRAINT PK_Users PRIMARY KEY([Id],[Username]) --COMBINING 2 COLUMNS AS A PK

ALTER TABLE[Users] --ADDING A CONSTRAINT TO CHECK FOR PASSWORD MIN LENGTH VALIDATION (YOU MAY SKIP "CONSTRAINT Constraint_Name" IF YOU LIKE AS SHOWN BELOW)
ADD CHECK(LEN([Password]) >= 5)

ALTER TABLE[Users] --ADDING A DEFAULT VALUE FOR A COLUMN (THE DEFAULT VALUE IN THIS CASE IS THE CURRENT DAYTIME THUS THE GETDATE() FUNCTION IS USED)
ADD DEFAULT GETDATE() FOR [LastLoginTime]

ALTER TABLE[Users]
DROP CONSTRAINT PK_Users

ALTER TABLE[Users]
ADD CONSTRAINT PK_Id PRIMARY KEY([Id])

ALTER TABLE[Users]
ADD CHECK(LEN([Username]) >=3)